### PR TITLE
Set up uart to read 1 byte at a time, and build a 30 byte message

### LINKED ISSUE #197: Circular buffer for science messages
branch off of /dev/science

### PR DESCRIPTION
**Pull request by WinsonChen114**

### CODE REVIEW

**Comment by jcp419** [comment]
Cool, did you test this and does it fix the garbage/noise issue on startup?

**Comment by wilsonchen02** [comment]
Not sure yet, it hasn't been tested. What's the garbage/noise issue?

**Comment by tabiosg** [comment]
> Not sure yet, it hasn't been tested. What's the garbage/noise issue?

Its the reason why we do this in the first issue. Basically there's noise on startup that messes up the buffer

**Comment by WinsonChen114** [comment]
Theoretically should fix it

**Review by tabiosg — APPROVED** [review]
Looks legit... should def test first.

**Pull request merged**
